namespace Origo.Bifrost.LanguageModels;
using Origo.Bifrost;

/// <summary>
/// Provides runtime help documentation for the LLM.Prompt.Complete message type.
/// </summary>
codeunit 10035397 "LLM Prompt Compl Help ori"
{
    Access = Internal;

    procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# LLM.Prompt.Complete');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('One-shot LLM completion. Sends a system prompt and user prompt to the configured provider and returns the text response. No tools are injected, no chat Bootstrap is applied, and no conversation state is returned.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('This is the **general-purpose compute step** for playbooks and scheduled tasks. Use it whenever a pipeline needs reasoning, transformation, or generation that no standard message type covers:');
        HelpBuilder.AppendLine('- **Date/time computation**: "What are the start and end dates for last month?"');
        HelpBuilder.AppendLine('- **Data comparison**: "Does address A match address B?" → Yes/No');
        HelpBuilder.AppendLine('- **Data transformation**: Compare structured data from prior steps → JSON update commands');
        HelpBuilder.AppendLine('- **Text generation**: Generate SMS, email body, or notification text from step data');
        HelpBuilder.AppendLine('- **Report formatting**: Format workspace data as HTML, Markdown, or plain text');
        HelpBuilder.AppendLine('- **Data extraction**: Extract fields from unstructured text, PDF content, or base64-encoded images');
        HelpBuilder.AppendLine('- **Translation**: Translate text to a target language');
        HelpBuilder.AppendLine('- **Classification**: Categorize input into predefined buckets');
        HelpBuilder.AppendLine('- **Decision routing**: "Should this customer get a reminder or collection notice?" based on aging data');
        HelpBuilder.AppendLine('- **Data enrichment**: Validate/normalize phone numbers, classify document types from OCR text');
        HelpBuilder.AppendLine('- **Filter generation**: Produce tableView filter strings or date ranges for subsequent Data.Records.Get steps');
        HelpBuilder.AppendLine('- **Format conversion**: Convert flat CSV/text to primaryKey/fields JSON for Data.Records.Set');
        HelpBuilder.AppendLine('- **Summarization**: Weekly sales summary, batch processing report, or error digest from prior step output');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Key principle**: When building a playbook, if there is no standard message type for a step, use `LLM.Prompt.Complete` as the glue. It bridges any gap between structured data steps.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Direction');
        HelpBuilder.AppendLine('Outbound');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Content Type');
        HelpBuilder.AppendLine('`text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('| Field | Type | Required | Description |');
        HelpBuilder.AppendLine('|-------|------|----------|-------------|');
        HelpBuilder.AppendLine('| prompt | Text | Yes | The user prompt — the task or question for the model |');
        HelpBuilder.AppendLine('| system | Text | No | System prompt that guides the model behavior. This is sent as-is — no Bootstrap or skill is injected. |');
        HelpBuilder.AppendLine('| roleCode | Code[20] | No | Bifrost Language Model code to use. Omit to use the caller''s configured or default language model. |');
        HelpBuilder.AppendLine('| file | Object | No | An inline file to send with the prompt: `{ "data": "<base64>", "mimeType": "image/png", "fileName": "invoice.png" }`. Passed to the provider as-is. Takes precedence over `attachment`. |');
        HelpBuilder.AppendLine('| attachment | Object | No | A file already stored in Business Central: `{ "table": "Incoming Document Attachment" \| "Document Attachment", "systemId": "<guid>" }`. The content is read, base64-encoded and the MIME type derived from the file extension. Ignored if `file` is supplied, or if the record is not found. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Not every provider accepts files — Copilot rejects them.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "prompt": "Extract the invoice number, date, and total from the following text:\n\nInvoice #4521\nDate: 2025-03-15\nTotal: $1,250.00",');
        HelpBuilder.AppendLine('  "system": "Extract structured data from text. Return valid JSON with keys: invoiceNo, date, total.",');
        HelpBuilder.AppendLine('  "roleCode": "CLAUDE"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Playbook Examples');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Date computation** (e.g. for filtering records by last month):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Return ONLY a JSON object with startDate and endDate in YYYY-MM-DD format. No explanation.",');
        HelpBuilder.AppendLine('  "prompt": "Today is 2026-08-30. What are the first and last day of last month?"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('→ `{"startDate":"2026-07-01","endDate":"2026-07-31"}`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Error notification SMS** (from playbook CUST-KT-SYNC step 12):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "roleCode": "KAPPI",');
        HelpBuilder.AppendLine('  "system": "Write a single SMS in Icelandic. Max 160 chars. No greeting. Return ONLY the SMS text.",');
        HelpBuilder.AppendLine('  "prompt": "Playbook CUST-KT-SYNC failed. Step 10 error: could not read customer records."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Data comparison with workspace refs** (step references prior step outputs via @stepNo):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Compare two addresses. Answer ONLY Yes or No.",');
        HelpBuilder.AppendLine('  "prompt": "BC: @_current.fields.Address, @_current.fields.PostCode @_current.fields.City\\nRegistry: @30.@_iter.street, @30.@_iter.postCode @30.@_iter.city"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Structured output from multi-step data** (LLM generates JSON update commands):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Compare BC addresses with registry. Return ONLY a JSON array of records to update. No explanation.",');
        HelpBuilder.AppendLine('  "prompt": "@10,20,30"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('→ Output is fed directly to a subsequent `Data.Records.Set` step.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Document classification** (classify incoming document from OCR/PDF text):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Classify the document. Return ONLY one of: Invoice, CreditMemo, DeliveryNote, PurchaseOrder, Unknown.",');
        HelpBuilder.AppendLine('  "prompt": "@10.text"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Decision routing** (determine action based on customer aging data):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Given customer balance and overdue days, return ONLY a JSON object: {action, reason}. Actions: Reminder, CollectionNotice, InternalEscalation, NoAction.",');
        HelpBuilder.AppendLine('  "prompt": "Customer 10000, balance 450000 ISK, 95 days overdue, 2 previous reminders sent."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Generate tableView filter** (compute dynamic filter for the next Data.Records.Get step):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Return ONLY a BC tableView filter string. No explanation.",');
        HelpBuilder.AppendLine('  "prompt": "Today is 2026-08-30. Filter Sales Invoice Header where Posting Date is in the previous fiscal quarter (April-June 2026) and Sell-to Customer No. starts with 1."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('→ `WHERE(Posting Date=FILTER(2026-04-01..2026-06-30),Sell-to Customer No.=FILTER(1*))`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Weekly summary email body** (format data from prior step as email HTML):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Create a professional HTML email body in Icelandic summarizing weekly sales. Use <table> for the data. Return ONLY the HTML.",');
        HelpBuilder.AppendLine('  "prompt": "@10"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Extract fields from scanned invoice image** (base64 image from prior step):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Extract invoice fields from the image. Return JSON: {vendorName, invoiceNo, date, totalAmount, currency}.",');
        HelpBuilder.AppendLine('  "prompt": "Extract from this invoice: @10.base64Image"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Payment reminder in Icelandic** (compose from customer balance data):');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "system": "Write a polite payment reminder in Icelandic. Include amount and due date. Max 500 chars. Return ONLY the text.",');
        HelpBuilder.AppendLine('  "prompt": "Customer: @_current.fields.Name, overdue amount: @10.fields.BalanceDueLCY, oldest due date: @10.fields.OldestDueDate"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('The provider''s response object is returned with `status` and `text` added. `text` is a copy of');
        HelpBuilder.AppendLine('the provider''s `reply`, so callers can read either. Any other property the provider returns');
        HelpBuilder.AppendLine('(token usage, model name) is passed through unchanged.');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "reply": "{\"invoiceNo\":\"4521\",\"date\":\"2025-03-15\",\"total\":1250.00}",');
        HelpBuilder.AppendLine('  "text": "{\"invoiceNo\":\"4521\",\"date\":\"2025-03-15\",\"total\":1250.00}"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Difference from the interactive Bifrost Chat');
        HelpBuilder.AppendLine('| | LLM.Prompt.Complete | Bifrost Chat (FactBox / Chat Focus) |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| Tools | None | Full MCP tool server |');
        HelpBuilder.AppendLine('| System prompt | Caller''s `system` only | Bootstrap + identity + language model skill |');
        HelpBuilder.AppendLine('| Record context | None | The record the chat was opened from |');
        HelpBuilder.AppendLine('| Conversation state | None | Kept for the session, multi-turn |');
        HelpBuilder.AppendLine('| Use case | Playbooks, scheduled tasks | Interactive chat |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Provider Resolution');
        HelpBuilder.AppendLine('1. If `roleCode` is supplied, uses that language model directly. An unknown code is an error —');
        HelpBuilder.AppendLine('   it does not fall through to the steps below.');
        HelpBuilder.AppendLine('2. Otherwise reads Bifrost Language Model Code from the user''s Bifrost User Setup');
        HelpBuilder.AppendLine('3. Falls back to the default language model (where Default = true)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Access');
        HelpBuilder.AppendLine('The caller needs the `BIFROST Chat ori` permission set (write permission on the Chat Gate).');
        HelpBuilder.AppendLine('`BIFROST LLM ori` alone is not enough — the chat gate is assigned explicitly.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('All errors are returned as `status: Error` with an `error` message; never as an HTTP failure.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Condition | Message |');
        HelpBuilder.AppendLine('|-----------|---------|');
        HelpBuilder.AppendLine('| Caller lacks the chat permission set | LLM prompt denied: missing ''Bifrost Chat'' permission set. |');
        HelpBuilder.AppendLine('| No `prompt` supplied | The "prompt" field is required. |');
        HelpBuilder.AppendLine('| `roleCode` not found | Bifrost Language Model "X" not found. |');
        HelpBuilder.AppendLine('| No provider configured | No chat provider configured. Set up a Bifrost Language Model with a Chat Provider. |');
        HelpBuilder.AppendLine('| Provider error (including Copilot not enabled, or a file sent to Copilot) | Error detail from the provider |');

        HelpText := HelpBuilder.ToText();
    end;
}
